### ISSUE TITLE
-ns flag ignored

### ISSUE THREAD

**Issue by dewet22** [timothycrosley/isort#394]
Despite #139 and #171 I still cannot get isort to include our `__init__.py` files:

```
$ isort -rc backend -vb -ns __init__.py -c | grep init
WARNING: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
WARNING: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
WARNING: __init__.py was skipped as it's listed in 'skip' setting or matches a glob in 'skip_glob' setting
$
```

`.isort.cfg` only contains:

```
[settings]
line_length=120
```

**Comment by dewet22** [comment]
Actually, looking at the other issues, adding it to `.isort.cfg` makes it work, leading me to believe the `-ns` flag is being ignored instead:

```
$ cat .isort.cfg
[settings]
line_length=120
not_skip = __init__.py
$ isort -rc backend -vb -c | grep init
SUCCESS: /.../__init__.py Everything Looks Good!
ERROR: /.../api/__init__.py Imports are incorrectly sorted.
ERROR: /.../models/__init__.py Imports are incorrectly sorted.
```

**Comment by timothycrosley** [comment]
Thanks for reporting, I'll work on getting this resolved!

**Comment by timothycrosley** [comment]
This should now be fixed in develop and make its way into the next release.
Thanks!

~Timothy

**Comment by manoadamro** [comment]
@timothycrosley This is still a problem
`isort -ns=./manager/__init__.py files=./manager/__init__.py`
`Skipped 1 files`

Is it safe to assume this is not going to be fixed?

**Comment by jdufresne** [comment]
The following works for me:

```py
$ isort -ns __init__.py ...
```

Can you give it a try?
