### ISSUE TITLE
`add_imports` option is broken

### ISSUE THREAD

**Issue by fyber** [timothycrosley/isort#651]
Just installed new version of `isort=4.3.0` (on python 3.6).
Given this file (`itest.py`):
```
from __future__ import absolute_import, unicode_literals

VAR = """
multiline text
"""
```
and this config in `setup.cfg`:
```
[isort]
add_imports =
    from __future__ import absolute_import
    from __future__ import unicode_literals
```
when I run `isort itest.py` I got this result:
```
from __future__ import absolute_import, unicode_literals

VAR = """
multiline text
"""

from __future__ import unicode_literals
from __future__ import absolute_import
```
When I run same command one more time the result is like this:
```
from __future__ import absolute_import, unicode_literals

VAR = """
multiline text
"""

from __future__ import unicode_literals
from __future__ import absolute_import

from __future__ import absolute_import
from __future__ import unicode_literals
```

If I remove `VAR` from that file and run isort again, the result is as expected:
```
from __future__ import absolute_import, unicode_literals
```
I believe this is a regression as I was unable to reproduce it in version `4.2.15`.
This bug makes new version unusable for us, since we have files with multiline strings and `add_imports` setting.

**Comment by adamchainz** [comment]
Also seeing this when upgrading in adamchainz/django-mysql#424

**Comment by timothycrosley** [comment]
This should now be fixed in release 4.3.1, Thank you!

**Comment by fyber** [comment]
I'm sorry, but looks like this is not fixed in version 4.3.1.
Output is the same as in my example above.

**Comment by adamchainz** [comment]
I'm afraid I'm also still seeing the same, updated my previously linked PR

**Comment by timothycrosley** [comment]
I'm so sorry! I didn't merge the fix in correctly before distributing the new release to PYPI, this should now be resolved in 4.3.2

**Comment by adamchainz** [comment]
Works for me thanks!

**Comment by adamchainz** [comment]
![](http://images2.fanpop.com/image/photos/8800000/Unicorn-Love-unicorns-8810157-400-390.gif)
