### ISSUE TITLE
noqa line not ignored

### ISSUE THREAD

**Issue by bnomis** [timothycrosley/isort#681]
The code below gives an error about the line `import app.models` But I think it should be OK because of the noqa comment above. This is with the setting `known_third_party = django
`

When using django we need to call django.setup() before importing any models. This is used a lot in standalone scripts. So this pattern is very common.

```python
#!/usr/bin/env python
from __future__ import print_function

import django
django.setup()  # noqa

import app.models


def main():
    app.models.objects.get(id=1)
    print('Hello')
```

Putting import/setup on one line:

```python
import django; django.setup()  # noqa
```

gives the same error.

I think when it's on one line, like the above isort, does not recognize it as a 3rd party library.

**Comment by Hnasar** [comment]
Good point. Sounds like a duplicate of #679.

**Comment by viniciusban** [comment]
I'm using a turnaround as long as isort can't handle it yet.

See the `if True:` block:

```
#!/usr/bin/env python
from __future__ import print_function

import django
django.setup()

if True:
    import app.models
```

**Comment by timothycrosley** [comment]
This should be fixed in the latest version of isort.

Thanks!

~Timothy

**Comment by markberger** [comment]
This still appears to be a problem in the latest release. isort says that my imports are incorrectly sorted with the following:

```python
import argparse

import django
from django.conf import settings
django.setup() # NOQA

from myapp.models import Model
```
